# Change these first
owner: dbroughton79 # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Microsoft 365 Admin Center
    url: https://admin.microsoft.com
  - name: Office 365 Status Page
    url: https://status.office365.com


status-website:
  baseUrl: /status-page
  name: IIT Service Status
  introTitle: "**IIT Service Status**"
  introMessage: "Live updates on Microsoft 365, and internal services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dbroughton79/status-page


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
